from common.constants import LanguageChoices

messages = {
    'greeting': '😊 Student assistant botga xush kelibsiz!',
    'restart bot': "🔄 Bot qayta ishga tushirildi",
    'select the language': "👇 Iltimos, tilni tanlang:",
    'uzbek': "🇺🇿 O'zbek",
    'english': "🇺🇸 English",
    "selected language doesn't exist": "👇 Ilitimos quyidagi mavjud tillardan birini tanlang:",

    'person emoji': '👤',
    'step emoji': '👣',
    'warning emoji': '⚠️',
    'condition emoji': '🛠',
    'next emoji': '⏭',
    'approved': '✅ Approved',
    'rejected': '❌ Rejected',
    'true icon': '✅',
    'false icon': '❌',

    LanguageChoices.UZBEK: {
        'language flag': '🇺🇿',
        'saved your language': "✅ Tanlangan til saqlandi",
        'change language': "Tilni o'zgartirish",
        'main menu': "🏠 Asosiy menu",
        'back button': '⬅️ Ortga',
        'skip': "⏭ O'tkazib yuborish",
        'cancel': '❌ Bekor qilish',
        'continue': "Davom etish ➡",
        'yes': "✅ Ha",
        'no': "❌ Yo'q",
        'saved': '✅ Saqlandi',
        'send number button': "📲 Telefon raqamni yuborish",
        'fill data': "📄 Ma'lumotlarni to'ldirish",
        'get full name': "To'liq ism va familyangizni kiriting.\n<i>Masalan: Mashrabov Mashhurbek Muhammdjon o'g'li</i>",
        'full name is too short': "⚠️ Ism va familya juda qisqa!",
        'full name is too long': "⚠️ Ism va familya juda uzun!",
        'verification sent': "🔍 Tutorga tasdiqlash so'rovi yuborildi. So'rovingiz tasdiqlangandan so'ng guruhga qo'shilasiz.",
        'you are approved': "🎉 Tabriklaymiz, siz tutor tomonidan tasdiqlandingiz",
        'you are rejected': "😔 Afsuski siz tutor tomonidan gurhga qo'shilish so'rovingiz rad etildi.",
        'select a group': "👇 Quyidagi guruhlardan birini tanlang:",
        'enter permanent address': "🏠 Doimiy yashash manzilingizni kiriting.\n<i>Masalan: Farg'ona viloyato, Marg'ilon shahar Shodlik ko'cha 31-uy</i>",
        'text is too short': "⚠️️ Matn juda qisqa!",
        'text is too long': "⚠️️ Matn juda uzun!",
        'enter rental address': "🏠 Ijaradagi yashash manzilingizni kiriting.\n<i>Masalan: Farg'ona viloyato, Farg'ona shahar shahar Sayilgoh ko'cha 65-uy</i>",
        'enter passport data': "🔒 Passport ma'lumotlaringizni kiriting.\n<i>Masalan: AB1234567, Marg'ilon IIB</i>",
        'enter phone number or click button': "<b>📲 Telefon raqamni yuborish</b> ni bosing yoki kirting.\n<i>Masalan: +998901234567</i>",
        'enter correct phone number': "Iltimos to'g'ri formatta kiriting.\n<i>Masalan: +998901234567</i>",
        'enter father data': "Otangizning ismi, familyasi va ish joyini kiriting.\n<i>Masalan: Abdullayev Akrom, haydovchi</i>",
        'enter father phone number': "Otangizning telefon raqamini kiriting.\n<i>Masalan: +998901234567</i>",
        'enter mother data': "Onangizning ismi, familyasi va ish joyini kiriting.\n<i>Masalan: Abdullayeva Nigora, uy bekasi</i>",
        'enter mother phone number': "Onangizning telefon raqamini kiriting.\n<i>Masalan: +998901234567</i>",
        'send photo': "Rasmingizni yuboring. <i>O'lchami 3x4</i>",
        'your information saved': "✅ Ma'lumotlaringiz muvaffaqiyatli saqlandi.",
        'sent request to join the group': "✅ Guruhga qo'shilish to'g'risidagi so'rovingiz tutorga yuborildi."
    },
    LanguageChoices.ENGLISH: {
        'language flag': '🇺🇸',
        'saved your language': '✅ Language saved',
        'change language': 'Change language',
        'main menu': "🏠 Main menu",
        'back button': '⬅️ Back',
        'groups': '👥 Groups',
        'skip': '⏭ Skip',
        'cancel': '❌ Cancel',
        'continue': "Continue ➡",
        'yes': "✅ Yes",
        'no': "❌ No",
        'saved': '✅ Saved',
        'send number button': "📲 Send number",
        'fill data': "📄 Fill in the information",
        'get full name': "Enter your full name.\n<i>Example: Mashrabov Mashhurbek Muhammdjon o'g'li</i>",
        'full name is too short': "⚠️ Full name is too short",
        'full name is too long': "⚠️ Full name is too long",
        'verification sent': "🔍 A confirmation requfenter correct phone numberest has been sent to a tutor. You will join the group after your request is approved.",
        'you are approved': "🎉 Congratulations, you have been approved by a tutor.",
        'you are rejected': "😔 Unfortunately, your request to join the group was rejected by the tutor.",
        'select a group': "👇 Choose one of the groups below:",
        'enter permanent address': "🏠 Enter your permanent address.\n<i>Example: Farg'ona viloyato, Marg'ilon shahar Shodlik ko'cha 31-uy</i>",
        'text is too short': "⚠️️ Text is too short",
        'text is too long': "⚠️️ Text is too long",
        'enter rental address': "🏠 Enter your rental address.\n<i>Example: Farg'ona viloyato, Farg'ona shahar Sayilgoh ko'cha 65-uy</i>",
        'enter passport data': "🔒 Enter your passport data.\n<i>Example: AB1234567, Marg'ilon IIB</i>",
        'enter phone number or click button': "Click the <b>📲 Send numberh</b> button or enter phone number.\n<i>Example: +998901234567</i>",
        'enter correct phone number': "Please enter the correct phone number.\n<i>Example: +998901234567</i>",
        'enter father data': "Enter your father's name, surname and job.\n<i>Example: Abdullayev Akrom, truck driver</i>",
        'enter father phone number': "Enter your father's phone number.\n<i>Example: +998901234567</i>",
        'enter mother data': "Enter your mother's name, surname and job.\n<i>Example: Abdullayevs Nigora, housewife</i>",
        'enter mother phone number': "Enter your mother's phone number.\n<i>Example: +998901234567</i>",
        'send photo': "Send a your photo. <i>Size should be 3x4</i>",
        'your information saved': "✅ Your information has been saved succesfully.",
        'sent request to join the group': "✅ Your request to join the group has been sent to the tutor.",
    },
}
