# Generated by Django 4.2.2 on 2023-06-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttelegramuser',
            name='language',
            field=models.CharField(blank=True, choices=[('uz', 'Uzbek'), ('en', 'English')], default='uz', max_length=5, null=True),
        ),
    ]
