# Generated by Django 4.2.2 on 2023-06-16 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_bot', '0003_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttelegramuser',
            name='father_data',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='studenttelegramuser',
            name='father_phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='studenttelegramuser',
            name='full_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studenttelegramuser',
            name='mother_data',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='studenttelegramuser',
            name='mother_phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='studenttelegramuser',
            name='passport_data',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='studenttelegramuser',
            name='permanent_address',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='studenttelegramuser',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='studenttelegramuser',
            name='photo_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studenttelegramuser',
            name='rental_address',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
