# Generated by Django 4.2.2 on 2023-06-16 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_bot', '0004_studenttelegramuser_father_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='student_bot.studenttelegramuser'),
        ),
    ]
