from common.constants import LanguageChoices

messages = {
    'greeting': '😊 Tutor assistant botga xush kelibsiz!',
    'restart bot': "🔄 Bot qayta ishga tushirildi",
    'select the language': "👇 Iltimos, tilni tanlang:",
    'uzbek': "🇺🇿 O'zbek",
    'english': "🇺🇸 English",
    "selected language doesn't exist": "👇 Ilitimos quyidagi mavjud tillardan birini tanlang:",

    'person emoji': '👤',
    'step emoji': '👣',
    'warning emoji': '⚠️',
    'condition emoji': '🛠',
    'next emoji': '⏭',
    'approved': '✅ Approved',
    'rejected': '❌ Rejected',
    'true icon': '✅',
    'false icon': '❌',

    LanguageChoices.UZBEK: {
        'language flag': '🇺🇿',
        'saved your language': "✅ Tanlangan til saqlandi",
        'change language': "Tilni o'zgartirish",
        'main menu': "🏠 Asosiy menu",
        'back button': '⬅️ Ortga',
        'groups': '👥 Guruhlar',
        'skip': "⏭ O'tkazib yuborish",
        'cancel': '❌ Bekor qilish',
        'continue': "Davom etish ➡",
        'yes': "✅ Ha",
        'no': "❌ Yo'q",
        'saved': '✅ Saqlandi',
        'get full name': "To'liq ism va familyangizni kiriting.\n<i>Masalan: Mashrabov Mashhurbek</i>",
        'full name is too short': "⚠️ Ism va familya juda qisqa!",
        'full name is too long': "⚠️ Ism va familya juda uzun!",
        'verification sent': "🔍 Moderatorga tasdiqlash so'rovi yuborildi. So'rovingiz tasdiqlangandan so'ng bot dan to'liq foydalanishingiz mumkin.",
        'you are approved': "🎉 Tabriklaymiz, siz moderator tomonidan tasdiqlandingiz. Botdan to'liq foydalanishingiz mumkin.",
        'you are rejected': "😔 Afsuski siz moderator tomonidan rad etildizgiz.",
        'you ware not verified': "⚠️ Siz botdan foydalanish uchun tasdiqlanmagansiz!",
        'get groups': "👇 Sizning guruhlaringiz:",
        'add group': "➕ Guruh qo'shish",
        'get group name': "Guruh nomini kiriting.\n<i>Masalan: 651-19</i>",
        'group name is too short': "⚠️ Guruh nomi juda qisqa.",
        'group name is too long': "⚠️ Guruh nomi juda uzun.",
        'request join group': "Ushbu talaba <b>{group_name}</b> guruhga qo'shilmoqchi. Uni tasdiqlaysizmi?\n<a href='{link}'>{student_name}</a>"
    },
    LanguageChoices.ENGLISH: {
        'language flag': '🇺🇸',
        'saved your language': '✅ Language saved',
        'change language': 'Change language',
        'main menu': "🏠 Main menu",
        'back button': '⬅️ Back',
        'groups': '👥 Groups',
        'skip': '⏭ Skip',
        'cancel': '❌ Cancel',
        'continue': "Continue ➡",
        'yes': "✅ Yes",
        'no': "❌ No",
        'saved': '✅ Saved',
        'get full name': "Enter your full name.\n<i>Example: Mashrabov Mashhurbek</i>",
        'full name is too short': "⚠️ Full name is too short",
        'full name is too long': "⚠️ Full name is too long",
        'verification sent': "🔍 A confirmation request has been sent to a moderator. Once your request is approved, you can fully use the bot.",
        'you are approved': "🎉 Congratulations, you have been approved by a moderator. You can fully use the bot.",
        'you are rejected': "😔 Unfortunately, you have been rejected by a moderator.",
        'you ware not verified': "⚠️ You are not yet verified by a moderator.",
        'get groups': "👇 Your groups:",
        'add group': "➕ Add group",
        'get group name': "Enter group name.\n<i>Example: 651-19</i>",
        'group name is too short': "⚠️ Group name is too short",
        'group name is too long': "⚠️ Group name is too long",
        'request join group': "This student wants to join to <b>{group_name}</b>. Do you approve?\n<a href='{link}'>{student_name}</a>"
    },
}
