from common.constants import LanguageChoices

messages = {
    'greeting': '😊 Tutor assistant botga xush kelibsiz!',
    'restart bot': "🔄 Bot qayta ishga tushirildi",
    'select the language': "👇 Iltimos, tilni tanlang:",
    'uzbek': "🇺🇿 O'zbek",
    'english': "🇺🇸 English",
    "selected language doesn't exist": "👇 Ilitimos quyidagi mavjud tillardan birini tanlang:",
    "saved your language": '',

    'person emoji': '👤',
    'step emoji': '👣',
    'warning emoji': '⚠️',
    'condition emoji': '🛠',
    'next emoji': '⏭',

    LanguageChoices.UZBEK: {
        'language flag': '🇺🇿',
        'saved your language': "✅ Tanlangan til saqlandi",
        'change language': "Tilni o'zgartirish",
        'main menu': "🏠 Asosiy menu",
        'back button': '⬅️ Ortga',
        'groups': '👥 Guruhlar',
        'skip': "⏭ O'tkazib yuborish",
        'cancel': '❌ Bekor qilish',
        'continue': "Davom etish ➡",
        'yes': "✅ Ha",
        'no': "❌ Yo'q",
        'saved': '✅ Saqlandi',
        'get full name': "To'liq ism va familyangizni kiriting.\n<i>Masalan: Mashrabov Mashhurbek</i>",
        'full name is too short': "⚠️ Ism va familya juda qisqa!",
        'full name is too long': "⚠️ Ism va familya juda uzun!",
    },
    LanguageChoices.ENGLISH: {
        'language flag': '🇺🇸',
        'saved your language': '✅ Language saved',
        'change language': 'Change language',
        'main menu': "🏠 Main menu",
        'back button': '⬅️ Back',
        'groups': '👥 Groups',
        'skip': '⏭ Skip',
        'cancel': '❌ Cancel',
        'continue': "Continue ➡",
        'yes': "✅ Yes",
        'no': "❌ No",
        'saved': '✅ Saved',
        'get full name': "Enter your full name.\n<i>Example: Mashrabov Mashhurbek</i>",
        'full name is too short': "⚠️ Full name is too short",
        'full name is too long': "⚠️ Full name is too long",
    },
}
